# Generated by Django 5.2.17 on 2026-09-23 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ats_identifier',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='ats_type',
            field=models.CharField(blank=True, choices=[('greenhouse', 'Greenhouse'), ('lever', 'Lever'), ('workday', 'Workday')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='career_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
